export const GET_PUBLIC_CUSTOM_POSTS_REQUEST = 'GET_PUBLIC_CUSTOM_POSTS_REQUEST';
export const GET_PUBLIC_CUSTOM_POSTS_SUCCESS = 'GET_PUBLIC_CUSTOM_POSTS_SUCCESS';
export const GET_PUBLIC_CUSTOM_POSTS_FAIL = 'GET_PUBLIC_CUSTOM_POSTS_FAIL';