import React, { forwardRef } from "react";
import { Bar, Pie, Line } from "react-chartjs-2";

// This component is designed for PDF export of the analytics dashboard.
// It receives all summary, chart, and filter data as props and renders a print-friendly layout.
// Usage: <AnalyticsExportPDFView ref={exportRef} summary={...} trends={...} composition={...} geolocation={...} relationships={...} filters={...} role={...} />

const DashboardCard = ({ title, value, icon, color, subtext }) => (
  <div
    style={{
      background: "#fff",
      borderLeft: `8px solid ${color}`,
      borderRadius: 12,
      boxShadow: "0 2px 8px #123F7B22",
      padding: 16,
      minWidth: 160,
      minHeight: 90,
      margin: 8,
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
    }}
  >
    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
      {icon && <span style={{ fontSize: 24 }}>{icon}</span>}
      <span style={{ fontWeight: 600, color: "#123F7B", fontSize: 16 }}>{title}</span>
    </div>
    <div style={{ fontSize: 28, fontWeight: 700, color: "#123F7B" }}>{value}</div>
    {subtext && <div style={{ fontSize: 12, color: "#888", marginTop: 4 }}>{subtext}</div>}
  </div>
);

const SectionTitle = ({ children }) => (
  <h2 style={{ color: "#123F7B", fontSize: 22, fontWeight: 700, margin: "24px 0 12px 0" }}>{children}</h2>
);

const AnalyticsExportPDFView = forwardRef(({
  summary,
  trends,
  composition,
  geolocation,
  relationships,
  filters,
  role
}, ref) => {
  return (
    <div ref={ref} style={{ background: "#f5f7fa", color: "#222", fontFamily: "Arial, sans-serif", padding: 32, minWidth: 900 }}>
      <h1 style={{ color: "#123F7B", fontSize: 32, fontWeight: 800, marginBottom: 8 }}>AgapayAlert Analytics Report</h1>
      <div style={{ fontSize: 16, color: "#555", marginBottom: 16 }}>
        <b>Role:</b> {role} &nbsp;|&nbsp; <b>Date:</b> {new Date().toLocaleString()}
      </div>
      {/* Filters summary */}
      <div style={{ background: "#fff", borderRadius: 8, padding: 16, marginBottom: 24, fontSize: 15 }}>
        <b>Filters Applied:</b><br />
        {Object.entries(filters || {}).map(([key, val]) => (
          <span key={key} style={{ marginRight: 16 }}>
            <b>{key}:</b> {Array.isArray(val) ? val.join(", ") : val || "All"}
          </span>
        ))}
      </div>
      {/* Summary Panel */}
      <SectionTitle>Summary</SectionTitle>
      <div style={{ display: "flex", flexWrap: "wrap" }}>
        {summary?.cards?.map((card, idx) => (
          <DashboardCard key={idx} {...card} />
        ))}
      </div>
      {/* Trends Section */}
      {trends && (
        <>
          <SectionTitle>Report Trends</SectionTitle>
          {trends.line && <Line data={trends.line.data} options={trends.line.options} />}
          {trends.bar && <Bar data={trends.bar.data} options={trends.bar.options} />}
        </>
      )}
      {/* Composition Section */}
      {composition && (
        <>
          <SectionTitle>Report Composition</SectionTitle>
          {composition.pie && <Pie data={composition.pie.data} options={composition.pie.options} />}
          {composition.stackedBar && <Bar data={composition.stackedBar.data} options={composition.stackedBar.options} />}
        </>
      )}
      {/* Geolocation Section */}
      {geolocation && (
        <>
          <SectionTitle>Geolocation Insights</SectionTitle>
          {/* You can render map images or summary tables here for PDF */}
          {geolocation.mapImage && <img src={geolocation.mapImage} alt="Heatmap" style={{ width: 600, margin: 16 }} />}
        </>
      )}
      {/* Relationships Section */}
      {relationships && (
        <>
          <SectionTitle>Relationships & Distribution</SectionTitle>
          {relationships.scatter && <Bar data={relationships.scatter.data} options={relationships.scatter.options} />}
          {relationships.dot && <Bar data={relationships.dot.data} options={relationships.dot.options} />}
        </>
      )}
      <div style={{ marginTop: 32, color: "#888", fontSize: 13, textAlign: "right" }}>
        Generated by AgapayAlert Analytics Dashboard
      </div>
    </div>
  );
});

export default AnalyticsExportPDFView;
